# This viminfo file was generated by Vim 7.3.
# You may edit it if you're careful!

# Value of 'encoding' when this file was written
*encoding=utf-8


# hlsearch on (H) or off (h):
~h
# Last Search Pattern:
~MSle0~/columns=

# Last Substitute Search Pattern:
~MSle0&-2

# Last Substitute String:
$

# Command Line History (newest to oldest):
:wq
:w
:e $MYVIMRC
:q
:bn
:bp
:bd
:e index.html
:BundleInstall
:PowerlineClearCache
:BundleClean!
:e ..\
:e www.qrsolutions.com\2col.html
:e assets\themes\business\less\style-responsive.less
:bn 
:e assets\themes\business\css\style.css
:e templates\splash.mustache
:w 
:set filetype=xml
:set filetype=xsl

# Search String History (newest to oldest):
?/columns=
?/columns
?/rows
?/set lines
?/les em
?/countdow
?/tc employ
?/welcome
?/back
? \<div\>
?/encod
?/status
?/fug
?/f3
?/numbers
?/vert
?/mousehi
?/folden
?/lines
?/macvim

# Expression History (newest to oldest):

# Input Line History (newest to oldest):
@p
@h4
@k
@h1
@h3
@C:\Program Files\Vim\vim73

# Input Line History (newest to oldest):

# Registers:
"0	LINE	0
	                            <div id="countdown_container" class="span-4">
	                                <div id="countdown_dashboard">
	                                    <div class="dash weeks_dash">
	                                        <span class="dash_title">semaines</span>
	                                        <div class="digit">0</div>
	                                        <div class="digit">0</div>
	                                    </div>
	
	                                    <div class="dash days_dash">
	                                        <span class="dash_title">jours</span>
	                                        <div class="digit">0</div>
	                                        <div class="digit">0</div>
	                                    </div>
	
	                                    <div class="dash hours_dash">
	                                        <span class="dash_title">heures</span>
	                                        <div class="digit">0</div>
	                                        <div class="digit">0</div>
	                                    </div>
	
	                                    <div class="dash minutes_dash">
	                                        <span class="dash_title">minutes</span>
	                                        <div class="digit">0</div>
	                                        <div class="digit">0</div>
	                                    </div>
	                                </div>
	                            </div>
	                            <script language="javascript" type="text/javascript">
	                                $(document).ready(function() {
	                                    $('#countdown_dashboard').countDown({
	                                        targetDate: {
	                                            'day':      14,
	                                            'month':    12,
	                                            'year':     2012,
	                                            'hour':     12,
	                                            'min':      0,
	                                            'sec':      0
	                                        }
	                                    });
	                                });
	                            </script>
"1	LINE	0
	Bundle 'Lokaltog/vim-easymotion'
	Bundle 'godlygeek/csapprox'
"2	LINE	0
	
"3	LINE	0
	
"4	LINE	0
	
"5	LINE	0
	
"6	LINE	0
	
"7	LINE	0
	                                    </div>
"8	LINE	0
	                                        <div class="digit">0</div>
"9	LINE	0
	                                        <div class="digit">0</div>
"a	LINE	0
	            #region Page Route
""-	CHAR	0
	0

# File marks:
'0  248  27  ~\_vimrc
'1  112  56  ~\_vimrc
'2  206  28  \\tcinfomaster\tcinforoot\groupecommunications\services\comm-electroniques\Editeurweb\monTC\menu.htm
'3  206  0  \\tcdevmaster\tcinfodev\groupecommunications\services\comm-electroniques\EditeurWeb\monTC\menu.htm
'4  238  57  \\tctestmaster\tcinfotest\communicationsgroup\services\ecomms\WebPublishing\myTC\menu.htm
'5  35  0  \\tcinfomaster\tcinfo\communicationsgroup\services\ecomms\WebPublishing\myTC\css\countdown.css
'6  28  0  ~\jVim\README.md
'7  24  0  ~\jVim\README.md
'8  27  32  ~\jVim\README.md
'9  44  25  c:\code\static\www.qrsolutions.com\index.html

# Jumplist (newest first):
-'  248  27  ~\_vimrc
-'  1  0  ~\_vimrc
-'  133  60  ~\_vimrc
-'  108  58  ~\_vimrc
-'  47  0  ~\_vimrc
-'  52  0  ~\_vimrc
-'  178  0  ~\_vimrc
-'  112  56  ~\_vimrc
-'  34  0  ~\_vimrc
-'  24  0  ~\_vimrc
-'  15  0  ~\_vimrc
-'  23  20  ~\_vimrc
-'  22  1  ~\_vimrc
-'  206  28  \\tcinfomaster\tcinforoot\groupecommunications\services\comm-electroniques\Editeurweb\monTC\menu.htm
-'  206  0  \\tctestmaster\tcinfotest\groupecommunications\services\comm-electroniques\EditeurWeb\monTC\menu.htm
-'  94  12  \\tcinfomaster\tcinforoot\groupecommunications\services\comm-electroniques\Editeurweb\monTC\menu.htm
-'  94  0  \\tctestmaster\tcinfotest\groupecommunications\services\comm-electroniques\EditeurWeb\monTC\menu.htm
-'  92  79  \\tcinfomaster\tcinforoot\groupecommunications\services\comm-electroniques\Editeurweb\monTC\menu.htm
-'  93  32  \\tcinfomaster\tcinforoot\groupecommunications\services\comm-electroniques\Editeurweb\monTC\menu.htm
-'  1  0  \\tcinfomaster\tcinforoot\groupecommunications\services\comm-electroniques\Editeurweb\monTC\menu.htm
-'  33  93  \\tcinfomaster\tcinforoot\groupecommunications\services\comm-electroniques\Editeurweb\monTC\menu.htm
-'  1  0  \\tctestmaster\tcinfotest\groupecommunications\services\comm-electroniques\EditeurWeb\monTC\menu.htm
-'  207  0  \\tctestmaster\tcinfotest\communicationsgroup\services\ecomms\WebPublishing\myTC\menu.htm
-'  234  81  \\tcinfomaster\tcinforoot\communicationsgroup\services\ecomms\WebPublishing\myTC\menu.htm
-'  233  29  \\tctestmaster\tcinfotest\communicationsgroup\services\ecomms\WebPublishing\myTC\menu.htm
-'  158  0  \\tctestmaster\tcinfotest\communicationsgroup\services\ecomms\WebPublishing\myTC\menu.htm
-'  248  0  \\tcinfomaster\tcinforoot\communicationsgroup\services\ecomms\WebPublishing\myTC\menu.htm
-'  1  0  \\tcinfomaster\tcinforoot\communicationsgroup\services\ecomms\WebPublishing\myTC\menu.htm
-'  94  0  \\tctestmaster\tcinfotest\communicationsgroup\services\ecomms\WebPublishing\myTC\menu.htm
-'  1  0  \\tctestmaster\tcinfotest\communicationsgroup\services\ecomms\WebPublishing\myTC\menu.htm
-'  206  0  \\tcdevmaster\tcinfodev\groupecommunications\services\comm-electroniques\EditeurWeb\monTC\menu.htm
-'  225  0  \\tctestmaster\tcinfotest\groupecommunications\services\comm-electroniques\EditeurWeb\monTC\menu.htm
-'  96  0  \\tctestmaster\tcinfotest\groupecommunications\services\comm-electroniques\EditeurWeb\monTC\menu.htm
-'  232  29  \\tcdevmaster\tcinfodev\groupecommunications\services\comm-electroniques\EditeurWeb\monTC\menu.htm
-'  180  32  \\tcdevmaster\tcinfodev\groupecommunications\services\comm-electroniques\EditeurWeb\monTC\menu.htm
-'  98  0  \\tcdevmaster\tcinfodev\groupecommunications\services\comm-electroniques\EditeurWeb\monTC\menu.htm
-'  94  0  \\tcdevmaster\tcinfodev\groupecommunications\services\comm-electroniques\EditeurWeb\monTC\menu.htm
-'  13  40  \\tctestmaster\tcinfotest\groupecommunications\services\comm-electroniques\EditeurWeb\monTC\menu.htm
-'  46  110  \\tcdevmaster\tcinfodev\groupecommunications\services\comm-electroniques\EditeurWeb\monTC\menu.htm
-'  1  0  \\tcdevmaster\tcinfodev\groupecommunications\services\comm-electroniques\EditeurWeb\monTC\menu.htm
-'  216  66  \\tcdevmaster\tcinfodev\groupecommunications\services\comm-electroniques\EditeurWeb\monTC\menu.htm
-'  236  29  \\tctestmaster\tcinfotest\communicationsgroup\services\ecomms\WebPublishing\myTC\menu.htm
-'  185  40  \\tctestmaster\tcinfotest\communicationsgroup\services\ecomms\WebPublishing\myTC\menu.htm
-'  168  28  \\tctestmaster\tcinfotest\communicationsgroup\services\ecomms\WebPublishing\myTC\menu.htm
-'  96  0  \\tcdevmaster\tcinfodev\groupecommunications\services\comm-electroniques\EditeurWeb\monTC\menu.htm
-'  97  0  \\tcdevmaster\tcinfodev\groupecommunications\services\comm-electroniques\EditeurWeb\monTC\menu.htm
-'  23  72  \\tcdevmaster\tcinfodev\groupecommunications\services\comm-electroniques\EditeurWeb\monTC\menu.htm
-'  29  0  \\tctestmaster\tcinfotest\communicationsgroup\services\ecomms\WebPublishing\myTC\css\countdown.css
-'  73  39  \\tcdevmaster\tcinfodev\communicationsgroup\services\ecomms\WebPublishing\myTC\menu.htm
-'  94  0  \\tcdevmaster\tcinfodev\communicationsgroup\services\ecomms\WebPublishing\myTC\menu.htm
-'  248  0  \\tcdevmaster\tcinfodev\communicationsgroup\services\ecomms\WebPublishing\myTC\menu.htm
-'  237  28  \\tcdevmaster\tcinfodev\communicationsgroup\services\ecomms\WebPublishing\myTC\menu.htm
-'  186  40  \\tcdevmaster\tcinfodev\communicationsgroup\services\ecomms\WebPublishing\myTC\menu.htm
-'  244  40  \\tcdevmaster\tcinfodev\communicationsgroup\services\ecomms\WebPublishing\myTC\menu.htm
-'  89  0  \\tcdevmaster\tcinfodev\communicationsgroup\services\ecomms\WebPublishing\myTC\menu.htm
-'  1  0  \\tcdevmaster\tcinfodev\communicationsgroup\services\ecomms\WebPublishing\myTC\menu.htm
-'  14  42  \\tctestmaster\tcinfotest\communicationsgroup\services\ecomms\WebPublishing\myTC\css\countdown.css
-'  35  83  \\tctestmaster\tcinfotest\communicationsgroup\services\ecomms\WebPublishing\myTC\menu.htm
-'  28  0  \\tctestmaster\tcinfotest\communicationsgroup\services\ecomms\WebPublishing\myTC\menu.htm
-'  22  0  \\tctestmaster\tcinfotest\communicationsgroup\services\ecomms\WebPublishing\myTC\css\countdown.css
-'  1  0  \\tctestmaster\tcinfotest\communicationsgroup\services\ecomms\WebPublishing\myTC\css\countdown.css
-'  238  57  \\tctestmaster\tcinfotest\communicationsgroup\services\ecomms\WebPublishing\myTC\menu.htm
-'  242  0  \\tctestmaster\tcinfotest\communicationsgroup\services\ecomms\WebPublishing\myTC\menu.htm
-'  247  0  \\tctestmaster\tcinfotest\communicationsgroup\services\ecomms\WebPublishing\myTC\menu.htm
-'  178  32  \\tctestmaster\tcinfotest\communicationsgroup\services\ecomms\WebPublishing\myTC\menu.htm
-'  194  66  \\tctestmaster\tcinfotest\communicationsgroup\services\ecomms\WebPublishing\myTC\menu.htm
-'  88  10  \\tctestmaster\tcinfotest\communicationsgroup\services\ecomms\WebPublishing\myTC\menu.htm
-'  35  0  \\tcinfomaster\tcinfo\communicationsgroup\services\ecomms\WebPublishing\myTC\css\countdown.css
-'  1  0  \\tcinfomaster\tcinfo\communicationsgroup\services\ecomms\WebPublishing\myTC\css\countdown.css
-'  28  0  ~\jVim\README.md
-'  1  0  ~\jVim\README.md
-'  206  0  \\tcdevmaster\tcinfodev\groupecommunications\services\comm-electroniques\EditeurWeb\monTC\menu.htm
-'  232  29  \\tcdevmaster\tcinfodev\groupecommunications\services\comm-electroniques\EditeurWeb\monTC\menu.htm
-'  180  32  \\tcdevmaster\tcinfodev\groupecommunications\services\comm-electroniques\EditeurWeb\monTC\menu.htm
-'  98  0  \\tcdevmaster\tcinfodev\groupecommunications\services\comm-electroniques\EditeurWeb\monTC\menu.htm
-'  94  0  \\tcdevmaster\tcinfodev\groupecommunications\services\comm-electroniques\EditeurWeb\monTC\menu.htm
-'  46  110  \\tcdevmaster\tcinfodev\groupecommunications\services\comm-electroniques\EditeurWeb\monTC\menu.htm
-'  1  0  \\tcdevmaster\tcinfodev\groupecommunications\services\comm-electroniques\EditeurWeb\monTC\menu.htm
-'  216  66  \\tcdevmaster\tcinfodev\groupecommunications\services\comm-electroniques\EditeurWeb\monTC\menu.htm
-'  96  0  \\tcdevmaster\tcinfodev\groupecommunications\services\comm-electroniques\EditeurWeb\monTC\menu.htm
-'  97  0  \\tcdevmaster\tcinfodev\groupecommunications\services\comm-electroniques\EditeurWeb\monTC\menu.htm
-'  23  72  \\tcdevmaster\tcinfodev\groupecommunications\services\comm-electroniques\EditeurWeb\monTC\menu.htm
-'  206  28  \\tcinfomaster\tcinforoot\groupecommunications\services\comm-electroniques\Editeurweb\monTC\menu.htm
-'  206  0  \\tctestmaster\tcinfotest\groupecommunications\services\comm-electroniques\EditeurWeb\monTC\menu.htm
-'  94  12  \\tcinfomaster\tcinforoot\groupecommunications\services\comm-electroniques\Editeurweb\monTC\menu.htm
-'  94  0  \\tctestmaster\tcinfotest\groupecommunications\services\comm-electroniques\EditeurWeb\monTC\menu.htm
-'  92  79  \\tcinfomaster\tcinforoot\groupecommunications\services\comm-electroniques\Editeurweb\monTC\menu.htm
-'  93  32  \\tcinfomaster\tcinforoot\groupecommunications\services\comm-electroniques\Editeurweb\monTC\menu.htm
-'  1  0  \\tcinfomaster\tcinforoot\groupecommunications\services\comm-electroniques\Editeurweb\monTC\menu.htm
-'  33  93  \\tcinfomaster\tcinforoot\groupecommunications\services\comm-electroniques\Editeurweb\monTC\menu.htm
-'  1  0  \\tctestmaster\tcinfotest\groupecommunications\services\comm-electroniques\EditeurWeb\monTC\menu.htm
-'  207  0  \\tctestmaster\tcinfotest\communicationsgroup\services\ecomms\WebPublishing\myTC\menu.htm
-'  234  81  \\tcinfomaster\tcinforoot\communicationsgroup\services\ecomms\WebPublishing\myTC\menu.htm
-'  248  27  ~\_vimrc
-'  1  0  ~\_vimrc
-'  133  60  ~\_vimrc
-'  108  58  ~\_vimrc

# History of marks within files (newest to oldest):

> ~\_vimrc
	"	248	27
	^	248	28
	.	248	27
	+	37	25
	+	38	28
	+	39	32
	+	40	5
	+	41	32
	+	42	43
	+	45	0
	+	46	0
	+	46	0
	+	47	0
	+	48	0
	+	50	19
	+	47	0
	+	46	8
	+	54	0
	+	68	25
	+	73	0
	+	75	0
	+	66	0
	+	65	0
	+	75	0
	+	75	0
	+	75	0
	+	75	0
	+	88	0
	+	86	21
	+	107	0
	+	126	0
	+	136	4
	+	46	0
	+	139	0
	+	139	0
	+	46	0
	+	139	0
	+	139	17
	+	106	0
	+	233	0
	+	234	0
	+	233	1
	+	240	0
	+	239	5
	+	249	0
	+	69	0
	+	75	0
	+	74	19
	+	85	0
	+	249	0
	+	247	0
	+	248	0
	+	249	0
	+	74	0
	+	76	10
	+	116	19
	+	106	0
	+	106	0
	+	106	5
	+	106	5
	+	106	5
	+	106	5
	+	106	5
	+	106	0
	+	108	14
	+	126	50
	+	127	43
	+	130	0
	+	129	21
	+	251	68
	+	253	0
	+	211	0
	+	145	0
	+	147	14
	+	149	0
	+	148	0
	+	152	0
	+	260	0
	+	106	5
	+	106	4
	+	106	4
	+	106	4
	+	106	4
	+	106	4
	+	18	1
	+	2	0
	+	21	30
	+	88	0
	+	106	0
	+	89	0
	+	101	4
	+	49	0
	+	78	0
	+	83	41
	+	237	0
	+	44	25
	+	43	4
	+	67	0
	+	69	0
	+	23	0
	+	30	0
	+	49	0
	+	248	27

> \\tctestmaster\tcinfotest\communicationsgroup\services\ecomms\WebPublishing\myTC\menu.htm
	"	207	0
	^	207	72
	.	238	57
	+	3	0
	+	94	0
	+	97	0
	+	94	73
	+	96	0
	+	95	58
	+	208	0
	+	234	59
	+	236	69
	+	247	0
	+	237	0
	+	242	0
	+	238	0
	+	239	0
	+	240	0
	+	241	0
	+	242	0
	+	243	0
	+	244	0
	+	237	0
	+	245	32
	+	244	35
	+	247	0
	+	245	34
	+	207	56
	+	233	32
	+	235	66
	+	246	34
	+	235	32
	+	236	0
	+	240	59
	+	239	57
	+	238	57
	+	234	57
	+	236	49
	+	208	0
	+	232	0
	+	207	71
	+	238	57

> \\tcinfomaster\tcinforoot\communicationsgroup\services\ecomms\WebPublishing\myTC\menu.htm
	"	234	81
	.	207	0
	+	3	0
	+	94	0
	+	207	0

> \\tctestmaster\tcinfotest\groupecommunications\services\comm-electroniques\EditeurWeb\monTC\menu.htm
	"	206	0
	^	96	0
	.	206	0
	+	3	0
	+	94	0
	+	96	0
	+	206	0

> \\tcinfomaster\tcinforoot\groupecommunications\services\comm-electroniques\Editeurweb\monTC\menu.htm
	"	206	28
	.	206	0
	+	3	0
	+	93	0
	+	94	0
	+	206	0

> \\tctestmaster\tcinfotest\communicationsgroup\services\ecomms\WebPublishing\myTC\css\countdown.css
	"	29	0
	.	14	24
	+	2	0
	+	14	24

> \\tcdevmaster\tcinfodev\communicationsgroup\services\ecomms\WebPublishing\myTC\menu.htm
	"	73	39
	^	96	0
	.	96	0
	+	3	0
	+	207	0
	+	248	0
	+	94	0
	+	96	0

> \\tcdevmaster\tcinfodev\groupecommunications\services\comm-electroniques\EditeurWeb\monTC\menu.htm
	"	206	0
	^	221	71
	.	221	70
	+	3	0
	+	97	0
	+	94	0
	+	96	0
	+	206	0
	+	209	72
	+	215	69
	+	221	70

> \\tcinfomaster\tcinfo\communicationsgroup\services\ecomms\WebPublishing\myTC\css\countdown.css
	"	35	0

> ~\jVim\README.md
	"	28	0
	^	31	66
	.	31	65
	+	8	6
	+	12	31
	+	32	0
	+	17	0
	+	32	0
	+	9	0
	+	12	0
	+	19	0
	+	11	0
	+	16	0
	+	15	0
	+	11	0
	+	17	24
	+	17	24
	+	18	0
	+	27	32
	+	23	13
	+	24	0
	+	31	65

> c:\code\static\www.qrsolutions.com\index.html
	"	44	25
	.	45	0
	+	60	0
	+	50	0
	+	31	0
	+	50	0
	+	45	0

> ~\jVim\[Vundle] Installer
	"	27	0
	.	1	0
	+	1	0

> C:\Console2\[Vundle] Installer
	"	26	0
	.	1	0
	+	1	0

> C:\Program Files\Vim\vim73\doc\help.txt
	"	1	0

> C:\Console2\sqlnet.log
	"	27	50

> C:\Console2\ControlP
	"	1	0
	.	1	0
	+	1	0
	+	1	0

> C:\Console2\[BufExplorer]
	"	1	0

> C:\Console2\[Vundle] clean
	"	3	0
	.	1	0
	+	1	0

> ~\[Vundle] Installer
	"	26	0
	.	1	0
	+	41	0
	+	26	0
	+	1	0

> ~\_viminfo
	"	1	0

> C:\Program Files\Vim\vim73\README.txt
	"	24	0

> C:\code\static\www.qrsolutions.com\qrsvc.html
	"	67	48
	^	112	50
	.	48	0
	+	61	0
	+	123	0
	+	172	0
	+	67	49
	+	68	60
	+	123	0
	+	123	0
	+	72	40
	+	123	40
	+	82	0
	+	123	0
	+	77	39
	+	76	33
	+	77	87
	+	78	0
	+	79	0
	+	80	0
	+	81	0
	+	84	0
	+	83	29
	+	123	0
	+	96	0
	+	52	0
	+	53	0
	+	58	0
	+	86	42
	+	97	0
	+	100	45
	+	112	49
	+	48	0

> C:\code\static\www.qrsolutions.com\2col.html
	"	54	0

> \\ncrws94\CMS\ASP\PlugIns\CGI\previewPage.aspx
	"	116	90

> ~\My Documents\Downloads\wet-boew-wet-boew-drupal-d8f433e\themes\tc_wetkit_adaptivetheme\css\global.styles.css
	"	1	0

> \\ncrws105\cms\ASP\PlugIns\CGI\searchPage.aspx
	"	2396	150
	^	2396	151
	.	2396	150
	+	2381	148
	+	2381	27
	+	2381	3
	+	2381	11
	+	2381	43
	+	2381	32
	+	2381	51
	+	2381	151
	+	2381	43
	+	2381	45
	+	2381	0
	+	2381	0
	+	2381	6
	+	2381	6
	+	2381	99
	+	2381	0
	+	2381	106
	+	2373	35
	+	2381	0
	+	2375	0
	+	2376	77
	+	2373	0
	+	2374	0
	+	2379	0
	+	2381	0
	+	2376	127
	+	2376	226
	+	2376	73
	+	2376	100
	+	2376	201
	+	2376	64
	+	2376	216
	+	2377	0
	+	2399	0
	+	2347	0
	+	2347	0
	+	2395	0
	+	2396	0
	+	2396	23
	+	2396	153
	+	2396	256
	+	2396	150

> \\ncrws94\cms\ASP\PlugIns\CGI\searchPage.aspx
	"	2402	20
	^	2388	85
	.	2388	84
	+	2378	0
	+	2378	0
	+	2378	0
	+	2378	0
	+	2374	0
	+	2375	0
	+	2401	0
	+	2375	122
	+	2401	0
	+	2394	0
	+	2401	110
	+	2401	79
	+	2401	0
	+	2401	139
	+	2375	0
	+	2386	0
	+	2389	8
	+	2375	8
	+	2389	0
	+	2394	0
	+	2401	45
	+	2401	32
	+	2384	0
	+	2377	0
	+	2386	37
	+	2401	0
	+	2401	0
	+	2401	151
	+	2375	0
	+	2375	122
	+	2375	0
	+	2401	80
	+	2401	0
	+	2401	29
	+	2401	0
	+	2401	32
	+	2401	35
	+	2401	0
	+	2396	0
	+	2375	0
	+	2375	122
	+	2399	155
	+	2397	129
	+	2396	8
	+	2397	125
	+	2388	91
	+	2389	63
	+	2387	91
	+	2389	69
	+	2388	85
	+	2389	71
	+	2388	84

> C:\xampp\htdocs\dev.local\templates\splash.mustache
	"	29	0
	^	53	54
	.	53	54
	+	37	150
	+	38	151
	+	24	0
	+	53	54

> C:\xampp\htdocs\dev.local\assets\themes\business\less\style.less
	"	178	15
	^	119	21
	.	178	0
	+	8	0
	+	1	41
	+	2	27
	+	4	22
	+	164	0
	+	158	0
	+	164	0
	+	159	0
	+	160	0
	+	162	0
	+	161	23
	+	161	27
	+	177	13
	+	178	21
	+	178	23
	+	178	0

> ~\My Documents\Downloads\jquery-wrap-captions\style.css
	"	32	0
	^	46	14
	.	34	0
	+	34	0

> ~\My Documents\Downloads\jquery-wrap-captions\index.html
	"	10	0

> C:\xampp\htdocs\dev.local\assets\themes\business\css\style.css
	"	172	0
	^	185	17
	.	184	27
	+	171	1
	+	172	8
	+	177	13
	+	177	28
	+	177	13
	+	183	20
	+	173	0
	+	178	0
	+	183	20
	+	184	0
	+	2	0
	+	184	27

> C:\xampp\htdocs\dev.local\assets\themes\business\less\style-responsive.less
	"	26	32
	^	26	33
	.	26	32
	+	2	0
	+	1	0
	+	2	0
	+	26	32

> \\ncrws99\CMS\ASP\PlugIns\CGI\searchPage.aspx
	"	2370	42

> \\ncrws94\CMS\ASP\PlugIns\CGI\XML\configuration.xml
	"	9	0

> \\ncrws105\CMS\ASP\PlugIns\CGI\XML\configuration.xml
	"	1	0

> ~\Desktop\sitemap.xsl
	"	7	0
	.	6	0
	+	1	0
	+	1	64
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	4	0
	+	6	0

> ~\My Documents\Downloads\zbar-0.10\INSTALL
	"	154	0

> ~\My Documents\Downloads\zbar-0.10\HACKING
	"	1	0

> ~\My Documents\Downloads\zbar-0.10\README.windows
	"	62	0

> C:\code\django\mysite\mysite\settings.py
	"	118	15
	^	118	16
	.	118	15
	+	14	44
	+	15	41
	+	122	11
	+	119	4
	+	118	15

> C:\code\django\mysite\polls\models.py
	"	10	32
	^	2	0
	.	11	0
	+	11	0
	+	3	0
	+	1	28
	+	11	0

> C:\code\django\mysite\mysite\urls.py
	"	19	0
	^	16	0
	.	16	0
	+	18	4
	+	5	0
	+	4	0
	+	16	0

> ~\Desktop\RedDot.css
	"	133	40
	^	133	41
	.	133	40
	+	134	42
	+	134	0
	+	134	35
	+	134	35
	+	134	41
	+	134	52
	+	134	80
	+	134	0
	+	134	99
	+	134	0
	+	134	116
	+	134	0
	+	128	19
	+	129	26
	+	132	0
	+	133	40

> C:\xampp\htdocs\dev.local\qa-theme\q2astrap\qa-theme.php
	"	96	0
	^	94	10
	.	100	0
	+	32	9
	+	123	0
	+	121	0
	+	122	0
	+	78	0
	+	100	0
	+	99	0
	+	90	0
	+	90	0
	+	84	91
	+	85	43
	+	85	73
	+	85	104
	+	86	18
	+	89	56
	+	89	9
	+	90	0
	+	95	9
	+	95	9
	+	89	0
	+	86	18
	+	100	0
	+	100	0
	+	100	0
	+	100	7
	+	100	41
	+	100	65
	+	100	0
	+	100	0
	+	100	0
	+	100	0
	+	100	0
	+	100	34
	+	95	9
	+	97	30
	+	82	0
	+	80	22
	+	81	22
	+	97	45
	+	81	63
	+	97	47
	+	95	8
	+	99	0
	+	100	0
	+	100	0
	+	35	0
	+	35	0
	+	76	0
	+	95	0
	+	95	0
	+	95	0
	+	95	0
	+	100	0
	+	95	0
	+	95	8
	+	87	72
	+	35	0
	+	35	0
	+	35	0
	+	35	0
	+	35	0
	+	35	0
	+	35	0
	+	34	0
	+	35	31
	+	35	0
	+	35	25
	+	35	20
	+	35	17
	+	35	16
	+	35	9
	+	35	22
	+	35	42
	+	87	70
	+	35	0
	+	95	0
	+	91	0
	+	91	0
	+	95	0
	+	93	0
	+	93	0
	+	95	0
	+	88	38
	+	97	30
	+	88	39
	+	35	40
	+	35	52
	+	91	9
	+	63	0
	+	62	0
	+	77	0
	+	66	0
	+	75	0
	+	74	21
	+	66	49
	+	74	18
	+	93	9
	+	94	9
	+	66	39
	+	100	0

> C:\xampp\htdocs\dev.local\qa-theme\q2astrap\qa-styles.css
	"	150	0
	^	6	43
	.	89	0
	+	1	0
	+	2	9
	+	3	17
	+	4	21
	+	5	21
	+	6	42
	+	8	22
	+	390	0
	+	11	0
	+	89	0

> C:\xampp\htdocs\dev.local\qa-theme\bootstrap\a-count-icon-ie6.png
	"	3	38

> C:\xampp\htdocs\dev.local\qa-theme\bootstrap\qa-theme.php
	"	84	29
	^	37	97
	.	37	97
	+	4	0
	+	41	23
	+	97	48
	+	103	28
	+	109	28
	+	28	0
	+	41	0
	+	64	0
	+	68	0
	+	71	0
	+	82	0
	+	70	0
	+	42	0
	+	63	0
	+	49	50
	+	52	0
	+	47	0
	+	48	0
	+	66	73
	+	41	0
	+	36	37
	+	37	97

> C:\xampp\htdocs\dev.local\qa-include\qa-theme-base.php
	"	324	0
	.	4	0
	+	4	0

> C:\xampp\htdocs\dev.local\qa-config.php
	"	36	32
	^	36	33
	.	36	32
	+	33	38
	+	34	33
	+	35	30
	+	36	32

> \\ncrws387\mytcdevroot\Views\WCMS\en-CA\jason.html
	"	1	0
	^	53	22
	.	68	0
	+	105	69
	+	105	23
	+	112	43
	+	189	43
	+	258	43
	+	261	43
	+	264	43
	+	267	43
	+	270	63
	+	105	23
	+	105	23
	+	105	0
	+	68	0
	+	68	81
	+	68	0
	+	68	80
	+	68	56
	+	68	56
	+	68	59
	+	68	59
	+	68	0
	+	68	0
	+	68	93
	+	68	18
	+	68	20
	+	68	24
	+	113	0
	+	113	44
	+	190	44
	+	259	44
	+	262	44
	+	265	44
	+	268	44
	+	113	0
	+	111	39
	+	110	0
	+	111	0
	+	105	0
	+	105	48
	+	105	39
	+	105	68
	+	68	37
	+	68	0
	+	68	0
	+	68	0
	+	105	44
	+	105	44
	+	105	44
	+	105	44
	+	105	44
	+	105	44
	+	105	44
	+	68	0
	+	68	29
	+	68	0
	+	68	0
	+	68	0
	+	110	70
	+	68	0
	+	68	0
	+	68	17
	+	68	0
	+	68	19
	+	68	0
	+	68	76
	+	68	51
	+	68	54
	+	68	100
	+	68	0
	+	68	0
	+	68	0
	+	68	0
	+	68	0
	+	68	0
	+	68	0
	+	68	0
	+	68	0
	+	68	0
	+	68	0
	+	68	0
	+	68	0
	+	68	0
	+	68	40
	+	56	0
	+	68	0
	+	68	0
	+	105	0
	+	51	0
	+	56	0
	+	53	1
	+	51	0
	+	53	20
	+	68	21
	+	114	0
	+	191	0
	+	257	0
	+	190	0
	+	68	20
	+	53	20
	+	68	0

> \\ncrws387\mytcaccroot\Views\WCMS\en-CA\longTitle.html
	"	158	131
	^	158	132
	.	158	131
	+	158	0
	+	22	115
	+	158	131

> C:\xampp\htdocs\dev.local\assets\themes\business\less\style1.less
	"	61	0
	^	116	1
	.	39	0
	+	26	13
	+	26	117
	+	26	13
	+	26	144
	+	9	41
	+	20	74
	+	21	74
	+	22	95
	+	23	77
	+	24	72
	+	25	69
	+	26	135
	+	26	11
	+	82	19
	+	15	27
	+	82	64
	+	85	0
	+	51	4
	+	50	6
	+	52	0
	+	55	14
	+	56	0
	+	54	15
	+	55	13
	+	66	65
	+	68	0
	+	75	65
	+	77	0
	+	83	59
	+	84	0
	+	76	10
	+	14	9
	+	15	10
	+	76	21
	+	80	0
	+	88	0
	+	117	0
	+	117	0
	+	42	1
	+	28	7
	+	29	0
	+	28	9
	+	29	4
	+	42	0
	+	17	8
	+	59	0
	+	58	17
	+	55	13
	+	51	27
	+	58	18
	+	57	0
	+	78	0
	+	85	0
	+	117	0
	+	67	0
	+	117	0
	+	117	0
	+	71	0
	+	64	0
	+	53	0
	+	69	0
	+	74	0
	+	81	0
	+	91	0
	+	43	0
	+	44	88
	+	48	0
	+	48	0
	+	48	0
	+	48	0
	+	48	0
	+	48	11
	+	48	8
	+	45	53
	+	46	0
	+	47	0
	+	48	0
	+	46	11
	+	47	8
	+	91	0
	+	90	36
	+	92	31
	+	93	34
	+	14	0
	+	13	16
	+	12	18
	+	11	13
	+	10	18
	+	8	18
	+	96	21
	+	59	0
	+	98	1
	+	101	0
	+	100	30
	+	105	23
	+	107	22
	+	109	1
	+	116	0
	+	115	16
	+	39	0

> C:\xampp\htdocs\dev.local\assets\themes\business\css\style1.css
	"	23	0
	.	121	0
	+	81	0
	+	121	0

> C:\xampp\htdocs\dev.local\assets\common\bootstrap\less\base.less
	"	1	0

> C:\xampp\htdocs\dev.local\assets\common\css\base.css
	"	32	16
	^	37	1
	.	37	0
	+	44	10
	+	22	0
	+	44	0
	+	44	0
	+	30	0
	+	31	32
	+	31	14
	+	32	13
	+	33	10
	+	22	1
	+	30	8
	+	22	0
	+	36	1
	+	37	0
	+	43	0
	+	37	0
	+	44	0
	+	37	0
	+	38	0
	+	29	0
	+	31	0
	+	24	0
	+	31	0
	+	35	0
	+	37	0

> ~\My Documents\Downloads\get.mustache
	"	36	38

> C:\xampp\htdocs\dev.local\assets\themes\redbourne\css\style.css
	"	101	33
	^	96	56
	.	96	55
	+	99	135
	+	99	168
	+	99	202
	+	99	231
	+	99	261
	+	99	0
	+	99	61
	+	99	61
	+	99	61
	+	99	42
	+	99	23
	+	99	41
	+	99	60
	+	99	61
	+	99	61
	+	99	101
	+	99	100
	+	99	97
	+	99	96
	+	99	93
	+	99	92
	+	99	66
	+	99	66
	+	72	37
	+	85	0
	+	99	0
	+	85	26
	+	72	48
	+	85	47
	+	72	49
	+	99	23
	+	99	41
	+	99	61
	+	72	17
	+	85	17
	+	72	26
	+	85	27
	+	72	61
	+	85	60
	+	71	48
	+	83	0
	+	84	31
	+	96	0
	+	99	60
	+	99	137
	+	74	0
	+	83	0
	+	72	62
	+	82	0
	+	99	0
	+	99	63
	+	99	24
	+	99	62
	+	99	90
	+	99	89
	+	99	115
	+	99	136
	+	99	0
	+	99	24
	+	74	0
	+	77	0
	+	80	0
	+	96	0
	+	85	62
	+	96	1
	+	96	21
	+	96	21
	+	96	25
	+	96	25
	+	96	13
	+	73	0
	+	86	0
	+	85	62
	+	95	0
	+	87	21
	+	88	21
	+	90	25
	+	91	25
	+	93	13
	+	94	13
	+	100	42
	+	96	20
	+	96	30
	+	100	0
	+	96	51
	+	96	32
	+	96	56
	+	96	31
	+	96	61
	+	96	58
	+	96	56
	+	96	33
	+	96	57
	+	99	0
	+	97	30
	+	98	27
	+	98	27
	+	99	0
	+	98	43
	+	96	55

> C:\xampp\htdocs\dev.local\tests\redbourne.php
	"	22	5
	.	22	0
	+	33	488
	+	12	39
	+	13	79
	+	15	0
	+	16	39
	+	17	22
	+	17	0
	+	17	461
	+	17	23
	+	17	22
	+	17	402
	+	17	22
	+	17	402
	+	17	404
	+	17	462
	+	17	461
	+	17	461
	+	17	465
	+	17	0
	+	17	465
	+	19	0
	+	20	36
	+	21	4
	+	21	32
	+	21	34
	+	21	102
	+	21	104
	+	21	121
	+	21	123
	+	21	152
	+	21	154
	+	21	177
	+	21	179
	+	21	194
	+	21	196
	+	21	212
	+	21	214
	+	21	289
	+	21	291
	+	21	305
	+	21	307
	+	21	445
	+	21	307
	+	21	450
	+	21	449
	+	21	472
	+	21	449
	+	21	21
	+	21	533
	+	21	532
	+	21	529
	+	21	536
	+	21	0
	+	21	536
	+	22	0
	+	27	36
	+	27	37
	+	27	244
	+	27	37
	+	27	249
	+	27	248
	+	27	257
	+	27	264
	+	27	260
	+	27	267
	+	27	294
	+	27	301
	+	27	323
	+	27	330
	+	27	351
	+	27	358
	+	27	413
	+	27	420
	+	27	417
	+	27	424
	+	27	457
	+	27	464
	+	27	484
	+	27	491
	+	27	512
	+	27	519
	+	27	565
	+	27	572
	+	27	569
	+	27	576
	+	27	647
	+	27	646
	+	27	645
	+	27	652
	+	27	0
	+	27	652
	+	27	0
	+	27	0
	+	27	5
	+	27	19
	+	13	119
	+	13	31
	+	32	47
	+	27	0
	+	22	0

> C:\xampp\htdocs\dev.local\tests\order.php
	"	11	5
	^	11	6
	.	11	5
	+	32	12
	+	38	1
	+	33	0
	+	41	0
	+	65	72
	+	65	59
	+	65	57
	+	65	59
	+	41	9
	+	65	0
	+	41	10
	+	42	0
	+	41	10
	+	42	0
	+	64	23
	+	65	0
	+	47	0
	+	39	36
	+	33	9
	+	34	20
	+	35	20
	+	36	20
	+	37	0
	+	39	0
	+	41	15
	+	41	0
	+	41	16
	+	41	0
	+	64	22
	+	46	1
	+	42	67
	+	43	69
	+	44	67
	+	45	69
	+	43	69
	+	44	67
	+	45	69
	+	41	16
	+	35	63
	+	41	0
	+	42	49
	+	43	51
	+	44	49
	+	45	51
	+	47	0
	+	51	0
	+	42	65
	+	51	23
	+	42	49
	+	51	35
	+	50	23
	+	51	1
	+	57	14
	+	50	34
	+	57	29
	+	50	28
	+	57	33
	+	57	3
	+	56	0
	+	55	71
	+	52	21
	+	58	0
	+	53	17
	+	57	29
	+	31	17
	+	40	26
	+	49	26
	+	48	71
	+	49	25
	+	58	1
	+	63	27
	+	22	0
	+	21	0
	+	22	85
	+	23	0
	+	31	30
	+	33	72
	+	33	10
	+	33	3
	+	33	24
	+	33	0
	+	33	0
	+	33	3
	+	33	0
	+	33	0
	+	31	17
	+	39	0
	+	39	0
	+	39	0
	+	39	0
	+	29	0
	+	30	2
	+	30	0
	+	29	8
	+	18	36
	+	20	54
	+	18	0
	+	62	33
	+	13	0
	+	11	5

> C:\xampp\htdocs\dev.local\templates\responsive.mustache
	"	50	0
	^	20	31
	.	20	30
	+	18	0
	+	72	28
	+	73	16
	+	76	0
	+	73	34
	+	73	50
	+	73	56
	+	73	50
	+	75	0
	+	73	35
	+	74	55
	+	11	30
	+	12	20
	+	15	20
	+	16	20
	+	20	0
	+	79	21
	+	80	21
	+	81	21
	+	82	21
	+	20	30

> C:\xampp\htdocs\dev.local\assets\common\css\base-responsive.css
	"	21	0
	^	30	13
	.	30	12
	+	2	0
	+	11	0
	+	10	0
	+	38	0
	+	15	14
	+	24	14
	+	33	14
	+	16	15
	+	25	15
	+	34	15
	+	15	14
	+	16	15
	+	24	14
	+	25	15
	+	12	4
	+	21	4
	+	30	4
	+	12	12
	+	21	12
	+	30	12

> \\ncrws387\mytcaccroot\Views\Shared\Includes\en-CA\wsmb.cshtml
	"	254	19
	.	254	19
	+	254	19

> \\ncrws387\mytcaccroot\Views\Shared\Includes\fr-CA\wsmb.cshtml
	"	228	19
	.	228	19
	+	228	19

> \\ncrws387\mytcdevroot\Views\Shared\Includes\en-CA\wsmb.cshtml
	"	254	19
	^	254	51
	.	254	19
	+	9	0
	+	8	19
	+	87	19
	+	158	19
	+	163	19
	+	191	19
	+	249	19
	+	251	47
	+	254	39
	+	256	47
	+	193	48
	+	254	19

> \\ncrws387\mytcdevroot\Views\Shared\Includes\fr-CA\wsmb.cshtml
	"	228	19
	.	228	19
	+	228	19

> \\ncrws387\mytcdevroot\Content\css\default.css
	"	347	0
	^	348	15
	.	355	4
	+	121	39
	+	122	38
	+	125	38
	+	126	38
	+	127	38
	+	128	38
	+	129	38
	+	219	0
	+	220	51
	+	118	32
	+	117	0
	+	224	108
	+	116	0
	+	224	147
	+	224	0
	+	224	104
	+	224	35
	+	225	16
	+	224	174
	+	224	87
	+	224	66
	+	224	90
	+	224	53
	+	224	87
	+	224	177
	+	224	64
	+	224	70
	+	224	85
	+	224	134
	+	224	128
	+	30	15
	+	30	0
	+	30	61
	+	235	0
	+	30	0
	+	29	62
	+	270	13
	+	5	102
	+	5	0
	+	2	0
	+	1	24
	+	5	121
	+	2	38
	+	4	0
	+	2	70
	+	3	92
	+	233	139
	+	119	0
	+	233	201
	+	125	0
	+	122	48
	+	122	71
	+	122	45
	+	125	84
	+	122	0
	+	125	0
	+	124	83
	+	124	0
	+	233	150
	+	123	86
	+	233	151
	+	123	63
	+	233	173
	+	120	47
	+	233	167
	+	233	0
	+	233	167
	+	233	0
	+	233	172
	+	123	108
	+	233	151
	+	123	63
	+	233	149
	+	123	63
	+	233	127
	+	123	85
	+	233	173
	+	120	31
	+	123	108
	+	233	114
	+	123	77
	+	120	0
	+	347	31
	+	356	0
	+	348	14
	+	349	15
	+	350	0
	+	351	0
	+	352	0
	+	353	0
	+	354	0
	+	355	0
	+	348	4
	+	349	4
	+	350	4
	+	351	4
	+	352	4
	+	353	4
	+	354	4
	+	355	4

> \\ncrws387\mytcaccroot\Content\css\default.css
	"	332	75
	.	346	0
	+	346	0
	+	346	0
	+	346	0

> \\ncrws387\mytcdevroot\Views\WCMS\en-CA\newSlider.html
	"	154	59
	.	68	73
	+	75	0
	+	68	82
	+	153	64
	+	165	65
	+	177	65
	+	153	61
	+	166	0
	+	166	0
	+	165	61
	+	177	61
	+	189	61
	+	68	45
	+	69	0
	+	68	72
	+	67	30
	+	74	43
	+	75	58
	+	158	71
	+	170	71
	+	75	0
	+	73	37
	+	74	45
	+	75	4
	+	75	0
	+	73	0
	+	73	39
	+	73	0
	+	73	107
	+	154	58
	+	166	58
	+	178	58
	+	189	0
	+	190	58
	+	73	59
	+	68	67
	+	67	78
	+	73	64
	+	74	56
	+	73	0
	+	67	76
	+	67	96
	+	67	54
	+	68	81
	+	74	58
	+	67	78
	+	150	68
	+	70	114
	+	71	80
	+	67	37
	+	67	50
	+	67	61
	+	67	79
	+	68	0
	+	71	42
	+	70	0
	+	71	0
	+	68	101
	+	71	40
	+	73	47
	+	73	0
	+	152	55
	+	158	44
	+	164	55
	+	170	44
	+	176	55
	+	182	44
	+	188	55
	+	194	44
	+	75	1
	+	75	0
	+	75	22
	+	75	22
	+	75	22
	+	75	22
	+	75	22
	+	75	22
	+	75	22
	+	75	22
	+	75	70
	+	68	73
	+	143	0
	+	75	0
	+	68	73

> ~\Desktop\sebnitu-HorizontalNav-60dfce6\index.html
	"	113	51

> \\ncrws387\mytcaccroot\Views\WCMS\en-CA\newSlider.html
	"	180	47
	^	189	202
	.	189	201
	+	153	141
	+	165	146
	+	177	117
	+	189	82
	+	189	201

> \\ncrws387\mytcdevroot\Views\WCMS\en-CA\jason1.html
	"	65	0
	.	141	0
	+	141	0

> \\ncrws387\mytcdevroot\Views\Shared\Includes\wsparams.cshtml
	"	1	0

> C:\xampp\htdocs\dev.local\templates\partials\order-datepicker.mustache
	"	7	6
	^	3	105
	.	3	104
	+	3	0
	+	4	0
	+	3	0
	+	4	0
	+	3	21
	+	3	0
	+	3	0
	+	2	0
	+	1	18
	+	7	5
	+	8	0
	+	2	0
	+	1	4
	+	7	5
	+	3	104

> C:\xampp\htdocs\dev.local\templates\partials\order-inputs.mustache
	"	1	0
	^	2	19
	.	2	18
	+	22	40
	+	22	57
	+	22	0
	+	22	33
	+	1	22
	+	38	5
	+	38	0
	+	1	0
	+	22	44
	+	1	0
	+	22	4
	+	1	0
	+	38	0
	+	22	0
	+	22	0
	+	22	0
	+	22	0
	+	22	0
	+	22	0
	+	22	0
	+	22	39
	+	22	39
	+	22	0
	+	22	39
	+	18	0
	+	18	0
	+	22	0
	+	17	0
	+	22	0
	+	22	0
	+	17	55
	+	17	55
	+	17	42
	+	17	38
	+	17	38
	+	17	27
	+	4	14
	+	18	14
	+	7	18
	+	17	0
	+	3	0
	+	18	0
	+	19	0
	+	17	0
	+	5	0
	+	18	0
	+	17	0
	+	7	43
	+	7	70
	+	5	35
	+	6	33
	+	7	0
	+	16	0
	+	17	0
	+	15	15
	+	17	0
	+	19	0
	+	20	0
	+	7	0
	+	15	0
	+	15	24
	+	15	56
	+	20	33
	+	7	29
	+	8	24
	+	9	33
	+	10	72
	+	13	33
	+	14	24
	+	15	0
	+	20	22
	+	38	24
	+	24	0
	+	38	0
	+	23	30
	+	37	0
	+	24	0
	+	23	51
	+	27	48
	+	7	46
	+	8	39
	+	7	96
	+	26	0
	+	27	0
	+	26	0
	+	26	91
	+	29	42
	+	1	17
	+	23	25
	+	26	54
	+	7	62
	+	15	32
	+	34	28
	+	7	74
	+	21	57
	+	22	0
	+	21	59
	+	20	26
	+	21	58
	+	2	18

> C:\xampp\htdocs\dev.local\assets\themes\order\css\style.css
	"	49	53
	^	5	17
	.	5	17
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	32
	+	1	28
	+	1	0
	+	1	0
	+	23	22
	+	24	0
	+	40	0
	+	41	0
	+	38	0
	+	40	0
	+	41	51
	+	50	0
	+	41	0
	+	41	0
	+	34	0
	+	31	0
	+	13	35
	+	47	33
	+	46	33
	+	49	51
	+	42	35
	+	43	41
	+	48	11
	+	40	0
	+	6	0
	+	5	17

> C:\xampp\htdocs\dev.local\templates\order.mustache
	"	50	51
	^	50	16
	.	50	15
	+	75	0
	+	76	0
	+	51	42
	+	64	27
	+	51	0
	+	51	0
	+	62	0
	+	65	0
	+	75	0
	+	51	0
	+	62	0
	+	64	0
	+	75	0
	+	76	0
	+	51	0
	+	76	13
	+	51	0
	+	76	0
	+	61	42
	+	61	0
	+	61	0
	+	61	21
	+	61	50
	+	61	53
	+	51	0
	+	51	0
	+	65	0
	+	64	30
	+	51	46
	+	65	28
	+	68	28
	+	86	0
	+	86	0
	+	49	0
	+	48	30
	+	77	0
	+	49	0
	+	64	34
	+	51	49
	+	89	0
	+	86	0
	+	55	32
	+	60	22
	+	55	22
	+	60	31
	+	61	0
	+	56	0
	+	52	32
	+	54	31
	+	52	28
	+	53	19
	+	52	3
	+	53	39
	+	88	48
	+	88	0
	+	88	0
	+	49	32
	+	68	100
	+	68	85
	+	68	66
	+	68	77
	+	68	41
	+	68	41
	+	68	75
	+	68	41
	+	68	0
	+	73	32
	+	71	111
	+	71	41
	+	70	36
	+	71	93
	+	72	0
	+	72	0
	+	71	116
	+	72	0
	+	71	0
	+	70	51
	+	71	37
	+	70	41
	+	87	77
	+	51	0
	+	51	0
	+	18	77
	+	31	0
	+	51	0
	+	51	0
	+	51	0
	+	51	0
	+	51	16
	+	51	0
	+	51	116
	+	51	0
	+	51	84
	+	51	90
	+	51	84
	+	51	0
	+	51	90
	+	51	84
	+	51	0
	+	50	15

> C:\xampp\htdocs\dev.local\assets\themes\order\js\app.js
	"	11	0
	^	13	20
	.	13	19
	+	14	2
	+	1	14
	+	2	38
	+	8	6
	+	8	0
	+	6	68
	+	2	35
	+	7	17
	+	4	62
	+	5	7
	+	6	22
	+	5	38
	+	4	46
	+	5	37
	+	11	6
	+	9	37
	+	10	33
	+	4	63
	+	3	44
	+	2	7
	+	13	19

> ~\My Documents\Visual Studio 2010\Projects\Intranet\Development\myTC\Views\WCMS\en-CA\jason.html
	"	170	41
	^	188	15
	.	149	0
	+	213	0
	+	284	0
	+	284	0
	+	284	0
	+	284	0
	+	284	0
	+	284	0
	+	275	0
	+	292	0
	+	285	0
	+	185	0
	+	164	0
	+	185	0
	+	185	0
	+	185	0
	+	185	0
	+	185	0
	+	185	0
	+	185	0
	+	185	0
	+	164	0
	+	185	24
	+	185	0
	+	165	0
	+	168	0
	+	167	0
	+	181	0
	+	181	0
	+	181	42
	+	181	28
	+	181	49
	+	181	28
	+	181	132
	+	181	28
	+	181	138
	+	181	28
	+	181	151
	+	181	28
	+	181	156
	+	181	28
	+	181	145
	+	181	0
	+	181	0
	+	181	0
	+	181	0
	+	181	0
	+	181	0
	+	178	28
	+	178	145
	+	179	0
	+	178	0
	+	179	0
	+	149	0

> C:\xampp\htdocs\dev.local\templates\partials\order-menu.mustache
	"	1	0
	^	20	18
	.	20	17
	+	17	0
	+	8	25
	+	8	0
	+	65	0
	+	11	18
	+	8	0
	+	65	0
	+	8	26
	+	15	0
	+	14	40
	+	16	52
	+	64	58
	+	50	0
	+	51	0
	+	39	0
	+	28	0
	+	18	0
	+	19	37
	+	19	46
	+	22	50
	+	23	0
	+	29	37
	+	29	42
	+	32	39
	+	33	34
	+	34	45
	+	37	25
	+	40	37
	+	40	43
	+	43	35
	+	44	39
	+	45	34
	+	48	25
	+	51	37
	+	54	20
	+	51	59
	+	54	68
	+	55	0
	+	56	33
	+	57	41
	+	58	38
	+	61	25
	+	7	29
	+	8	0
	+	63	0
	+	7	24
	+	8	28
	+	18	28
	+	28	28
	+	39	28
	+	50	28
	+	8	41
	+	9	0
	+	11	0
	+	9	55
	+	11	15
	+	9	55
	+	11	0
	+	18	36
	+	28	36
	+	39	36
	+	50	36
	+	19	15
	+	19	52
	+	9	90
	+	19	87
	+	19	0
	+	29	15
	+	29	0
	+	40	15
	+	40	82
	+	40	0
	+	51	15
	+	51	87
	+	51	0
	+	9	0
	+	10	0
	+	9	54
	+	19	51
	+	21	0
	+	19	0
	+	20	0
	+	19	51
	+	29	0
	+	31	0
	+	30	0
	+	29	47
	+	40	49
	+	41	0
	+	40	48
	+	51	64
	+	52	0
	+	41	0
	+	30	0
	+	10	43
	+	20	46
	+	30	43
	+	41	43
	+	52	43
	+	20	17

> \\ncrws387\mytcdevroot\Content\css\default-ie.css
	"	11	50
	^	11	51
	.	11	0
	+	10	0
	+	11	0
	+	12	0
	+	11	54
	+	12	0
	+	11	0
	+	12	0
	+	11	0

> C:\xampp\htdocs\dev.local\templates\partials\order-input.mustache
	"	2	0
	.	2	0
	+	2	0

> C:\xampp\htdocs\dev.local\tests\base.php
	"	11	5
	^	34	56
	.	35	0
	+	31	37
	+	30	10
	+	31	0
	+	30	38
	+	31	72
	+	32	26
	+	32	252
	+	33	21
	+	34	55
	+	35	0

> C:\xampp\htdocs\dev.local\tests\_preloader.php
	"	1	0
	.	17	0
	+	23	0
	+	32	0
	+	25	39
	+	31	0
	+	21	34
	+	25	25
	+	31	25
	+	31	0
	+	21	31
	+	20	56
	+	21	20
	+	20	1
	+	33	0
	+	24	21
	+	2	0
	+	9	0
	+	8	13
	+	7	14
	+	8	51
	+	11	0
	+	20	0
	+	25	8
	+	31	0
	+	30	5
	+	29	0
	+	29	0
	+	31	0
	+	28	59
	+	8	0
	+	20	40
	+	21	8
	+	25	26
	+	28	33
	+	3	12
	+	28	50
	+	4	12
	+	12	2
	+	16	2
	+	10	52
	+	16	25
	+	19	0
	+	19	1
	+	17	0
	+	19	0
	+	17	0

> C:\xampp\htdocs\dev.local\assets\common\js\base-responsive.js
	"	1	0
	.	1	0
	+	1	0

> C:\xampp\htdocs\dev.local\assets\themes\redbourne\js\responsive.js
	"	1	0
	.	1	0
	+	1	0

> C:\xampp\htdocs\dev.local\templates\2pass.mustache
	"	85	0
	^	64	34
	.	82	72
	+	54	50
	+	54	0
	+	35	0
	+	69	21
	+	55	0
	+	54	45
	+	51	40
	+	54	46
	+	69	0
	+	75	33
	+	82	68
	+	63	0
	+	63	0
	+	63	0
	+	64	33
	+	68	0
	+	63	18
	+	68	18
	+	63	31
	+	68	31
	+	82	72

> C:\xampp\htdocs\order.local\index.php
	"	26	0
	^	21	35
	.	5	16
	+	5	16

> C:\xampp\htdocs\order.local\tests\_preloader.php
	"	25	1
	^	20	51
	.	20	50
	+	3	0
	+	6	0
	+	17	26
	+	20	33
	+	13	8
	+	12	36
	+	20	50

> C:\xampp\htdocs\order.local\tests\order.php
	"	15	0
	^	29	42
	.	31	0
	+	36	22
	+	28	34
	+	29	41
	+	31	0

> C:\xampp\htdocs\order.local\templates\order.mustache
	"	60	0
	^	17	92
	.	53	0
	+	77	29
	+	77	29
	+	77	29
	+	77	29
	+	77	29
	+	77	30
	+	77	30
	+	77	30
	+	77	30
	+	77	0
	+	77	0
	+	3	0
	+	77	0
	+	3	0
	+	1	0
	+	61	0
	+	67	33
	+	22	0
	+	16	50
	+	21	0
	+	18	0
	+	17	0
	+	17	91
	+	51	0
	+	53	0

> C:\xampp\htdocs\order.local\assets\themes\order\css\style.css
	"	37	38

> C:\xampp\htdocs\order.local\tests\lunchpro.php
	"	40	24
	^	6	35
	.	6	34
	+	31	58
	+	5	14
	+	7	0
	+	6	34

> \\ncrws387\mytcaccroot\Views\WCMS\en-CA\jason.html
	"	10	6
	^	3	0
	.	2	0
	+	21	36
	+	39	18
	+	40	45
	+	41	135
	+	28	0
	+	1	0
	+	7	5
	+	8	36
	+	10	6
	+	4	0
	+	2	0

> C:\xampp\apache\conf\extra\httpd-vhosts.conf
	"	50	17
	^	46	39
	.	46	39
	+	46	39

> C:\xampp\htdocs\dev.local\tests\qrs_api.php
	"	211	0

> ~\Desktop\themed.htm
	"	1	0

> C:\Program Files\Vim\vimfiles\syntax\htmljinja.vim
	"	12	0

> C:\Program Files\Vim\vim73\syntax\html.vim
	"	248	4
	^	248	5
	.	248	4
	+	248	4

> C:\xampp\htdocs\dev.local\index.php
	"	15	24
	^	19	36
	.	20	41
	+	34	16
	+	34	36
	+	34	35
	+	34	36
	+	34	59
	+	34	62
	+	34	93
	+	34	96
	+	34	97
	+	34	104
	+	34	97
	+	34	108
	+	34	120
	+	34	131
	+	34	150
	+	34	157
	+	34	157
	+	34	160
	+	34	165
	+	34	168
	+	34	168
	+	34	175
	+	34	169
	+	34	180
	+	34	215
	+	34	226
	+	34	237
	+	34	244
	+	34	242
	+	34	242
	+	34	0
	+	34	249
	+	34	242
	+	34	253
	+	34	271
	+	34	282
	+	34	293
	+	34	300
	+	34	298
	+	34	305
	+	34	298
	+	34	309
	+	34	325
	+	34	336
	+	34	347
	+	34	354
	+	34	352
	+	34	359
	+	34	352
	+	34	357
	+	34	0
	+	34	363
	+	34	381
	+	34	392
	+	34	404
	+	34	411
	+	34	409
	+	34	416
	+	34	409
	+	34	420
	+	34	436
	+	34	418
	+	34	0
	+	34	447
	+	34	455
	+	34	462
	+	34	464
	+	34	467
	+	34	476
	+	34	475
	+	34	484
	+	34	0
	+	34	483
	+	1	0
	+	8	0
	+	34	0
	+	11	0
	+	30	0
	+	20	0
	+	28	0
	+	29	0
	+	12	0
	+	5	19
	+	4	0
	+	5	18
	+	8	13
	+	10	3
	+	30	5
	+	23	47
	+	20	54
	+	20	58
	+	18	16
	+	15	22
	+	13	3
	+	18	51
	+	19	55
	+	25	0
	+	20	0
	+	19	35
	+	20	41
